module.exports = {
    // CreateConsultantProfile: require('./CreateProfile'),
    // CreateConsultingCompanyProfile: require('./CreateConsultingCompanyProfile'),
    // RequestClientAuth: require('./RequestClientAuth'),
    // CreateConsultantProfileTemp: require('./CreateConsultantProfileTemp'),
    // CreateConsultingCompanyProfileTemp: require('./CreateConsultingCompanyProfileTemp'),
    // CheckProfileTempExist: require('./CheckProfileTempExist'),
    // GetProfile: require('./GetProfile'),
    // GetProfileTemp: require('./GetProfileTemp'),
    // DeleteProfileTemp: require('./DeleteProfileTemp'),
    CreateProfile: require('./CreateProfile'),
    GetProfiles: require('./GetProfiles'),
    GetMyProfile: require('./GetMyProfile'),
    GetProfile: require('./GetProfile'),
    UpdateProfile: require('./UpdateProfile'),
};
